Don´t store any backup job failed
giantswarm/etcd-backup pull request #29
Opened 2019-02-06 15:24 UTC by ferrandinand

References  https://github.com/giantswarm/giantswarm/issues/5222

To remove alerts for etcd backups failed jobs.

The behaviour will be the following:
- A job will start a pod defined in the cronjob for etcd backup.
If the pod returns an error it will retry the same operation 6 times(default backoffLimit), then if the last pod had an error status too, job and pods involved will be removed and don't kept in kubectl get jobs command.

You can still see that there is a problem checking the age of the last completed job.

We need to keep an eye on TTL if it hits the stable version
[https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/)

2019-02-07 05:58 UTC, calvix requested changes
this would hide any issues related to failing job, and  we need to know when etcd-backup fails as it means we have no backup

In order to clean up old failed jobs we should rather use this:
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#ttl-mechanism-for-finished-jobs
Where we set the TTL to something like  22 or 23 hours, in that case, we will get behavior:
* if the job is failing  every run we still get alerts
* if the job failed once time for an unknown reason it won't alert us  the next day

2019-02-07 05:59 UTC, calvix commented
FYI: you can request a review from sigs, ie: you can request review from `sig-infrastructure` or from `sig-monitoring`

2019-02-07 08:35 UTC, ferrandinand commented
TTL seems to be the best option but do we feel fine relying on a 1.12 alpha feature? If yes, we can change without any doubt.

If not we must do a tradeoff maybe pushing this issue https://github.com/giantswarm/giantswarm/issues/5297

2019-02-07 08:41 UTC, JosephSalisbury commented
TIL about `ttlSecondsAfterFinished` - that's a neat feature

2019-02-07 08:49 UTC, corest commented
`ttlSecondsAfterFinished` seems to be fine for me. With alerting on stale backups of course. But that's a different issue

2019-02-07 08:49 UTC, calvix commented
Yeah, I would say we are fine with that, in worst case scenario it will vanish and we will be back to the state that we are now.

In general, a lot of features that k8s has are in Alpha/Beta stages but they are fine and we are using them.

If none has veto than i would go with that.

2019-02-07 14:21 UTC, ferrandinand commented
This must be deployed first in order to use tilSecondsAfterFinished

https://github.com/giantswarm/hive/pull/413
https://github.com/giantswarm/giantnetes-terraform/pull/199

2019-02-08 07:26 UTC, calvix approved these changes
lgtm if tested :)

2019-08-30 07:25 UTC, corest commented
@ferrandinand are you going to merge this? It pops up every day in my pull reminders

2019-09-05 07:22 UTC, corest commented
@ferrandinand ?

2019-09-10 13:04 UTC, ferrandinand commented
This was already changed some time ago. Sorry

2019-09-10 13:04 UTC, closed without merging